-- VIEW_USER_INFORMATION
CREATE VIEW VIEW_USER_INFORMATION(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE) AS
SELECT CAST(USERS.USER_ID AS VARCHAR2(100)), USERS.FIRST_NAME, USERS.LAST_NAME, CAST(USERS.YEAR_OF_BIRTH AS NUMBER(38)), CAST(USERS.MONTH_OF_BIRTH AS NUMBER(38)), CAST(USERS.DAY_OF_BIRTH AS NUMBER(38)), USERS.GENDER, CC.CITY_NAME, CC.STATE_NAME, CC.COUNTRY_NAME, HC.CITY_NAME, HC.STATE_NAME, HC.COUNTRY_NAME, PROGRAM.INSTITUTION, CAST(EDUCATION.PROGRAM_YEAR AS NUMBER(38)), CAST(PROGRAM.CONCENTRATION AS CHAR(100)), PROGRAM.DEGREE
FROM USERS
LEFT JOIN USER_CURRENT_CITY ON USERS.USER_ID = USER_CURRENT_CITY.USER_ID
LEFT JOIN CITIES CC ON USER_CURRENT_CITY.CURRENT_CITY_ID = CC.CITY_ID
LEFT JOIN USER_HOMETOWN_CITY ON USERS.USER_ID = USER_HOMETOWN_CITY.USER_ID
LEFT JOIN CITIES HC ON USER_HOMETOWN_CITY.HOMETOWN_CITY_ID = HC.CITY_ID
LEFT JOIN EDUCATION ON USERS.USER_ID = EDUCATION.USER_ID
LEFT JOIN PROGRAMS ON EDUCATION.PROGRAM_ID = PROGRAMS.PROGRAM_ID;

-- VIEW_ARE_FRIENDS
CREATE VIEW VIEW_ARE_FRIENDS(USER1_ID, USER2_ID) AS
SELECT CAST(USER1_ID AS VARCHAR2(100)), CAST(USER2_ID AS VARCHAR2(100))
FROM FRIENDS; 

-- VIEW_PHOTO_INFORMATION
CREATE VIEW VIEW_PHOTO_INFORMATION(ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK) AS
SELECT ALBUMS.ALBUM_ID, CAST(ALBUMS.ALBUM_OWNER_ID AS VARCHAR2(100)), ALBUMS.COVER_PHOTO_ID, ALBUMS.ALBUM_NAME, ALBUMS.ALBUM_CREATED_TIME, ALBUMS.ALBUM_MODIFIED_TIME, ALBUMS.ALBUM_LINK, ALBUMS.ALBUM_VISIBILITY, PHOTOS.PHOTO_ID, PHOTOS.PHOTO_CAPTION, PHOTOS.PHOTO_CREATED_TIME, PHOTOS.PHOTO_MODIFIED_TIME, PHOTOS.PHOTO_LINK 
FROM ALBUMS
LEFT JOIN PHOTOS ON ALBUMS.ALBUM_ID = PHOTOS.ALBUM_ID;

-- VIEW_EVENT_INFORMATION
CREATE VIEW VIEW_EVENT_INFORMATION(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME) AS
SELECT CAST(USER_EVENTS.EVENT_ID AS VARCHAR2(100)), CAST(USER_EVENTS.EVENT_CREATOR_ID AS VARCHAR2(100)), USER_EVENTS.EVENT_NAME, USER_EVENTS.EVENT_TAGLINE, USER_EVENTS.EVENT_DESCRIPTION, USER_EVENTS.EVENT_HOST, USER_EVENTS.EVENT_TYPE, USER_EVENTS.EVENT_SUBTYPE, USER_EVENTS.EVENT_ADDRESS, CITIES.CITY_NAME, CITIES.STATE_NAME, CITIES.COUNTRY_NAME, USER_EVENTS.EVENT_START_TIME, USER_EVENTS.EVENT_END_TIME
FROM USER_EVENTS LEFT JOIN CITIES ON USER_EVENTS.EVENT_CITY_ID = CITIES.CITY_ID;

-- VIEW_TAG_INFORMATION
CREATE VIEW VIEW_TAG_INFORMATION(PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE) AS
SELECT TAG_PHOTO_ID, CAST(TAG_SUBJECT_ID AS VARCHAR2(100)), TAG_CREATED_TIME, TAG_X, TAG_Y
FROM TAGS;

